import type { Book } from "../types";

export const books: Book[] = [
  {
    id: "universal-computer-on",
    track: "universal",
    title: "Компьютер включен, что дальше?",
    funnyTitle: "Компьютер включен, что дальше?",
    level: 1,
    price: 40,
    durationDays: 2,
    qualificationPoints: 10,
  },
  {
    id: "qa-click-break",
    track: "qa",
    title: "Нажми сюда и посмотри что сломается",
    funnyTitle: "Нажми сюда и посмотри что сломается",
    level: 1,
    price: 80,
    durationDays: 3,
    qualificationPoints: 20,
  },
  {
    id: "qa-release-break",
    track: "qa",
    title: "Искусство ломать релиз до релиза",
    funnyTitle: "Искусство ломать релиз до релиза",
    level: 3,
    price: 220,
    durationDays: 7,
    qualificationPoints: 42,
    unlockRequirements: { track: "qa", minLevel: 2 },
  },
  {
    id: "backend-api-teapots",
    track: "backend",
    title: "API для чайников и их родственников",
    funnyTitle: "API для чайников и их родственников",
    level: 1,
    price: 100,
    durationDays: 4,
    qualificationPoints: 22,
  },
  {
    id: "backend-distributed-cows",
    track: "backend",
    title: "Распределенные коровы и отказоустойчивые сараи",
    funnyTitle: "Распределенные коровы и отказоустойчивые сараи",
    level: 4,
    price: 390,
    durationDays: 11,
    qualificationPoints: 72,
    unlockRequirements: { track: "backend", minLevel: 3 },
  },
  {
    id: "frontend-align-button",
    track: "frontend",
    title: "CSS и 40 способов выровнять кнопку",
    funnyTitle: "CSS и 40 способов выровнять кнопку",
    level: 1,
    price: 95,
    durationDays: 4,
    qualificationPoints: 22,
  },
  {
    id: "frontend-state-soul",
    track: "frontend",
    title: "Состояние приложения и состояние души",
    funnyTitle: "Состояние приложения и состояние души",
    level: 3,
    price: 255,
    durationDays: 8,
    qualificationPoints: 47,
    unlockRequirements: { track: "frontend", minLevel: 2 },
  },
  {
    id: "pm-calls-existence",
    track: "pm",
    title: "Созвон как форма существования",
    funnyTitle: "Созвон как форма существования",
    level: 1,
    price: 90,
    durationDays: 4,
    qualificationPoints: 20,
  },
  {
    id: "pm-manage-chaos",
    track: "pm",
    title: "Управление хаосом в малых дозах",
    funnyTitle: "Управление хаосом в малых дозах",
    level: 3,
    price: 265,
    durationDays: 9,
    qualificationPoints: 48,
    unlockRequirements: { track: "pm", minLevel: 2 },
  },
  {
    id: "pentest-ethical-domophone",
    track: "pentester",
    title: "Этичный взлом для тех, кто случайно вскрыл домофон",
    funnyTitle: "Этичный взлом для тех, кто случайно вскрыл домофон",
    level: 1,
    price: 110,
    durationDays: 4,
    qualificationPoints: 24,
  },
  {
    id: "analyst-fate-tables",
    track: "analyst",
    title: "Таблички судьбы и диаграммы рока",
    funnyTitle: "Таблички судьбы и диаграммы рока",
    level: 1,
    price: 85,
    durationDays: 3,
    qualificationPoints: 20,
  },
  {
    id: "analyst-gauss-household",
    track: "analyst",
    title: "Многополярная матрица Гаусса для бытовых нужд",
    funnyTitle: "Многополярная матрица Гаусса для бытовых нужд",
    level: 5,
    price: 560,
    durationDays: 15,
    qualificationPoints: 108,
    unlockRequirements: { track: "analyst", minLevel: 4 },
  },
  {
    id: "cto-people-and-systems",
    track: "cto",
    title: "Архитектура систем, людей и случайных решений",
    funnyTitle: "Архитектура систем, людей и случайных решений",
    level: 5,
    price: 650,
    durationDays: 16,
    qualificationPoints: 110,
  },
];

