import type { Book } from "../types";

const bookPriceMultiplier = 10;

const baseBooks: Book[] = [
  {
    id: "universal-computer-on",
    track: "universal",
    title: "Компьютер включен, что дальше?",
    funnyTitle: "Компьютер включен, что дальше?",
    level: 1,
    price: 40,
    durationDays: 2,
    qualificationPoints: 10,
  },
  {
    id: "universal-no-cry-logs",
    track: "universal",
    title: "Как не плакать над логами",
    funnyTitle: "Как не плакать над логами",
    level: 1,
    price: 60,
    durationDays: 3,
    qualificationPoints: 12,
  },
  {
    id: "universal-table-mail-deadline",
    track: "universal",
    title: "Таблица, письмо и дедлайн",
    funnyTitle: "Таблица, письмо и дедлайн",
    level: 1,
    price: 75,
    durationDays: 3,
    qualificationPoints: 12,
  },
  {
    id: "universal-professional-suffering",
    track: "universal",
    title: "Введение в профессиональное страдание",
    funnyTitle: "Введение в профессиональное страдание",
    level: 1,
    price: 90,
    durationDays: 4,
    qualificationPoints: 15,
  },
  {
    id: "qa-click-break",
    track: "qa",
    title: "Нажми сюда и посмотри что сломается",
    funnyTitle: "Нажми сюда и посмотри что сломается",
    level: 1,
    price: 80,
    durationDays: 3,
    qualificationPoints: 20,
  },
  {
    id: "qa-100-bugs-scared-dev",
    track: "qa",
    title: "Сто багов и один испуганный разработчик",
    funnyTitle: "Сто багов и один испуганный разработчик",
    level: 1,
    price: 95,
    durationDays: 4,
    qualificationPoints: 22,
  },
  {
    id: "qa-login-form-pain",
    track: "qa",
    title: "Форма логина как источник боли",
    funnyTitle: "Форма логина как источник боли",
    level: 2,
    price: 140,
    durationDays: 5,
    qualificationPoints: 28,
  },
  {
    id: "qa-oy-button-durability",
    track: "qa",
    title: "Проверка кнопки \"Ой\" на прочность",
    funnyTitle: "Проверка кнопки \"Ой\" на прочность",
    level: 2,
    price: 155,
    durationDays: 5,
    qualificationPoints: 30,
  },
  {
    id: "qa-release-break",
    track: "qa",
    title: "Искусство ломать релиз до релиза",
    funnyTitle: "Искусство ломать релиз до релиза",
    level: 3,
    price: 220,
    durationDays: 7,
    qualificationPoints: 42,
    unlockRequirements: { track: "qa", minLevel: 2 },
  },
  {
    id: "qa-brave-tired-test-cases",
    track: "qa",
    title: "Тест-кейсы для храбрых и уставших",
    funnyTitle: "Тест-кейсы для храбрых и уставших",
    level: 3,
    price: 240,
    durationDays: 8,
    qualificationPoints: 45,
    unlockRequirements: { track: "qa", minLevel: 2 },
  },
  {
    id: "qa-bug-loop-no-tire",
    track: "qa",
    title: "Как гонять баги по кругу и не уставать",
    funnyTitle: "Как гонять баги по кругу и не уставать",
    level: 4,
    price: 330,
    durationDays: 10,
    qualificationPoints: 65,
    unlockRequirements: { track: "qa", minLevel: 3 },
  },
  {
    id: "qa-automation-moral-superiority",
    track: "qa",
    title: "Автоматизация ради морального превосходства",
    funnyTitle: "Автоматизация ради морального превосходства",
    level: 4,
    price: 360,
    durationDays: 11,
    qualificationPoints: 70,
    unlockRequirements: { track: "qa", minLevel: 3 },
  },
  {
    id: "qa-air-bugs-black-belt",
    track: "qa",
    title: "Черный пояс по поиску багов в воздухе",
    funnyTitle: "Черный пояс по поиску багов в воздухе",
    level: 5,
    price: 480,
    durationDays: 14,
    qualificationPoints: 95,
    unlockRequirements: { track: "qa", minLevel: 4 },
  },
  {
    id: "qa-absurd-systems-audit",
    track: "qa",
    title: "Верховный аудит абсурдных систем",
    funnyTitle: "Верховный аудит абсурдных систем",
    level: 5,
    price: 520,
    durationDays: 15,
    qualificationPoints: 105,
    unlockRequirements: { track: "qa", minLevel: 4 },
  },
  {
    id: "backend-api-teapots",
    track: "backend",
    title: "API для чайников и их родственников",
    funnyTitle: "API для чайников и их родственников",
    level: 1,
    price: 100,
    durationDays: 4,
    qualificationPoints: 22,
  },
  {
    id: "backend-server-lied-down",
    track: "backend",
    title: "Сервер не упал, он просто прилег",
    funnyTitle: "Сервер не упал, он просто прилег",
    level: 1,
    price: 110,
    durationDays: 4,
    qualificationPoints: 24,
  },
  {
    id: "backend-crud-farming",
    track: "backend",
    title: "CRUD и прочие сельскохозяйственные практики",
    funnyTitle: "CRUD и прочие сельскохозяйственные практики",
    level: 2,
    price: 170,
    durationDays: 6,
    qualificationPoints: 32,
  },
  {
    id: "backend-databases-stubborn",
    track: "backend",
    title: "Базы данных для упрямых",
    funnyTitle: "Базы данных для упрямых",
    level: 2,
    price: 185,
    durationDays: 6,
    qualificationPoints: 34,
  },
  {
    id: "backend-microservices-divorce",
    track: "backend",
    title: "Микросервисы и развод по контейнерам",
    funnyTitle: "Микросервисы и развод по контейнерам",
    level: 3,
    price: 260,
    durationDays: 8,
    qualificationPoints: 48,
    unlockRequirements: { track: "backend", minLevel: 2 },
  },
  {
    id: "backend-queues-caches",
    track: "backend",
    title: "Как не утонуть в очередях и кэшах",
    funnyTitle: "Как не утонуть в очередях и кэшах",
    level: 3,
    price: 280,
    durationDays: 9,
    qualificationPoints: 50,
    unlockRequirements: { track: "backend", minLevel: 2 },
  },
  {
    id: "backend-distributed-cows",
    track: "backend",
    title: "Распределенные коровы и отказоустойчивые сараи",
    funnyTitle: "Распределенные коровы и отказоустойчивые сараи",
    level: 4,
    price: 390,
    durationDays: 11,
    qualificationPoints: 72,
    unlockRequirements: { track: "backend", minLevel: 3 },
  },
  {
    id: "backend-no-panic-highload",
    track: "backend",
    title: "Бэкенд без паники под высокой нагрузкой",
    funnyTitle: "Бэкенд без паники под высокой нагрузкой",
    level: 4,
    price: 420,
    durationDays: 12,
    qualificationPoints: 76,
    unlockRequirements: { track: "backend", minLevel: 3 },
  },
  {
    id: "backend-intergalactic-barn-architecture",
    track: "backend",
    title: "Архитектура межгалактического коровника",
    funnyTitle: "Архитектура межгалактического коровника",
    level: 5,
    price: 560,
    durationDays: 15,
    qualificationPoints: 105,
    unlockRequirements: { track: "backend", minLevel: 4 },
  },
  {
    id: "backend-server-magic-big-logs",
    track: "backend",
    title: "Серверная магия и закон больших логов",
    funnyTitle: "Серверная магия и закон больших логов",
    level: 5,
    price: 600,
    durationDays: 16,
    qualificationPoints: 112,
    unlockRequirements: { track: "backend", minLevel: 4 },
  },
  {
    id: "frontend-align-button",
    track: "frontend",
    title: "CSS и 40 способов выровнять кнопку",
    funnyTitle: "CSS и 40 способов выровнять кнопку",
    level: 1,
    price: 95,
    durationDays: 4,
    qualificationPoints: 22,
  },
  {
    id: "frontend-html-no-tears",
    track: "frontend",
    title: "HTML без слез и дивов отчаяния",
    funnyTitle: "HTML без слез и дивов отчаяния",
    level: 1,
    price: 100,
    durationDays: 4,
    qualificationPoints: 23,
  },
  {
    id: "frontend-js-already-tired",
    track: "frontend",
    title: "JavaScript для тех, кто уже устал",
    funnyTitle: "JavaScript для тех, кто уже устал",
    level: 2,
    price: 165,
    durationDays: 6,
    qualificationPoints: 31,
  },
  {
    id: "frontend-forms-modals-traps",
    track: "frontend",
    title: "Формы, модалки и прочие ловушки",
    funnyTitle: "Формы, модалки и прочие ловушки",
    level: 2,
    price: 180,
    durationDays: 6,
    qualificationPoints: 34,
  },
  {
    id: "frontend-state-soul",
    track: "frontend",
    title: "Состояние приложения и состояние души",
    funnyTitle: "Состояние приложения и состояние души",
    level: 3,
    price: 255,
    durationDays: 8,
    qualificationPoints: 47,
    unlockRequirements: { track: "frontend", minLevel: 2 },
  },
  {
    id: "frontend-max-min",
    track: "frontend",
    title: "Фронтенд на максималках и минималках",
    funnyTitle: "Фронтенд на максималках и минималках",
    level: 3,
    price: 275,
    durationDays: 9,
    qualificationPoints: 50,
    unlockRequirements: { track: "frontend", minLevel: 2 },
  },
  {
    id: "frontend-brave-interfaces-design",
    track: "frontend",
    title: "Проектирование интерфейсов для особенно смелых",
    funnyTitle: "Проектирование интерфейсов для особенно смелых",
    level: 4,
    price: 380,
    durationDays: 11,
    qualificationPoints: 72,
    unlockRequirements: { track: "frontend", minLevel: 3 },
  },
  {
    id: "frontend-design-system-suffering",
    track: "frontend",
    title: "Компоненты, темы и дизайн-системы страдания",
    funnyTitle: "Компоненты, темы и дизайн-системы страдания",
    level: 4,
    price: 410,
    durationDays: 12,
    qualificationPoints: 75,
    unlockRequirements: { track: "frontend", minLevel: 3 },
  },
  {
    id: "frontend-pixels-responsibility",
    track: "frontend",
    title: "Великий трактат о пикселях и ответственности",
    funnyTitle: "Великий трактат о пикселях и ответственности",
    level: 5,
    price: 550,
    durationDays: 15,
    qualificationPoints: 104,
    unlockRequirements: { track: "frontend", minLevel: 4 },
  },
  {
    id: "frontend-orbital-samovar",
    track: "frontend",
    title: "Интерфейсы для орбитального самовара",
    funnyTitle: "Интерфейсы для орбитального самовара",
    level: 5,
    price: 590,
    durationDays: 16,
    qualificationPoints: 110,
    unlockRequirements: { track: "frontend", minLevel: 4 },
  },
  {
    id: "pm-calls-existence",
    track: "pm",
    title: "Созвон как форма существования",
    funnyTitle: "Созвон как форма существования",
    level: 1,
    price: 90,
    durationDays: 4,
    qualificationPoints: 20,
  },
  {
    id: "pm-write-tasks-sane",
    track: "pm",
    title: "Как записывать задачи и не сойти с ума",
    funnyTitle: "Как записывать задачи и не сойти с ума",
    level: 1,
    price: 100,
    durationDays: 4,
    qualificationPoints: 22,
  },
  {
    id: "pm-deadline-myths",
    track: "pm",
    title: "Дедлайн: мифы и легенды",
    funnyTitle: "Дедлайн: мифы и легенды",
    level: 2,
    price: 160,
    durationDays: 6,
    qualificationPoints: 30,
  },
  {
    id: "pm-yesterday-plan",
    track: "pm",
    title: "Табличка правды и план на вчера",
    funnyTitle: "Табличка правды и план на вчера",
    level: 2,
    price: 175,
    durationDays: 6,
    qualificationPoints: 33,
  },
  {
    id: "pm-team-release-panic",
    track: "pm",
    title: "Команда, релиз и легкая паника",
    funnyTitle: "Команда, релиз и легкая паника",
    level: 3,
    price: 245,
    durationDays: 8,
    qualificationPoints: 46,
    unlockRequirements: { track: "pm", minLevel: 2 },
  },
  {
    id: "pm-manage-chaos",
    track: "pm",
    title: "Управление хаосом в малых дозах",
    funnyTitle: "Управление хаосом в малых дозах",
    level: 3,
    price: 265,
    durationDays: 9,
    qualificationPoints: 48,
    unlockRequirements: { track: "pm", minLevel: 2 },
  },
  {
    id: "pm-12-projects",
    track: "pm",
    title: "Как вести 12 проектов и не исчезнуть",
    funnyTitle: "Как вести 12 проектов и не исчезнуть",
    level: 4,
    price: 370,
    durationDays: 11,
    qualificationPoints: 70,
    unlockRequirements: { track: "pm", minLevel: 3 },
  },
  {
    id: "pm-agree-impossible",
    track: "pm",
    title: "Согласование несогласуемого",
    funnyTitle: "Согласование несогласуемого",
    level: 4,
    price: 395,
    durationDays: 12,
    qualificationPoints: 74,
    unlockRequirements: { track: "pm", minLevel: 3 },
  },
  {
    id: "pm-upper-management",
    track: "pm",
    title: "Высший менеджмент для тех, кто пережил все",
    funnyTitle: "Высший менеджмент для тех, кто пережил все",
    level: 5,
    price: 530,
    durationDays: 15,
    qualificationPoints: 100,
    unlockRequirements: { track: "pm", minLevel: 4 },
  },
  {
    id: "pm-status-roadmap",
    track: "pm",
    title: "Империя статусов и великий roadmap",
    funnyTitle: "Империя статусов и великий roadmap",
    level: 5,
    price: 570,
    durationDays: 16,
    qualificationPoints: 108,
    unlockRequirements: { track: "pm", minLevel: 4 },
  },
  {
    id: "pentest-ethical-domophone",
    track: "pentester",
    title: "Этичный взлом для тех, кто случайно вскрыл домофон",
    funnyTitle: "Этичный взлом для тех, кто случайно вскрыл домофон",
    level: 1,
    price: 110,
    durationDays: 4,
    qualificationPoints: 24,
  },
  {
    id: "pentest-passwords-holes-guilt",
    track: "pentester",
    title: "Пароли, дыры и чувство вины",
    funnyTitle: "Пароли, дыры и чувство вины",
    level: 1,
    price: 120,
    durationDays: 4,
    qualificationPoints: 25,
  },
  {
    id: "pentest-careful-digital-breakin",
    track: "pentester",
    title: "Введение в аккуратный цифровой взлом",
    funnyTitle: "Введение в аккуратный цифровой взлом",
    level: 2,
    price: 180,
    durationDays: 6,
    qualificationPoints: 34,
  },
  {
    id: "pentest-find-hole-not-fall",
    track: "pentester",
    title: "Как найти дыру и не упасть в нее самому",
    funnyTitle: "Как найти дыру и не упасть в нее самому",
    level: 2,
    price: 195,
    durationDays: 6,
    qualificationPoints: 36,
  },
  {
    id: "pentest-network-packets",
    track: "pentester",
    title: "Сетевые пакеты и прочие подозрительные сущности",
    funnyTitle: "Сетевые пакеты и прочие подозрительные сущности",
    level: 3,
    price: 275,
    durationDays: 8,
    qualificationPoints: 49,
    unlockRequirements: { track: "pentester", minLevel: 2 },
  },
  {
    id: "pentest-security-nobody-asked",
    track: "pentester",
    title: "Безопасность, которой никто не просил",
    funnyTitle: "Безопасность, которой никто не просил",
    level: 3,
    price: 290,
    durationDays: 9,
    qualificationPoints: 52,
    unlockRequirements: { track: "pentester", minLevel: 2 },
  },
  {
    id: "pentest-red-team-common-sense",
    track: "pentester",
    title: "Красная команда против здравого смысла",
    funnyTitle: "Красная команда против здравого смысла",
    level: 4,
    price: 400,
    durationDays: 11,
    qualificationPoints: 74,
    unlockRequirements: { track: "pentester", minLevel: 3 },
  },
  {
    id: "pentest-audit-important-cutlets",
    track: "pentester",
    title: "Продвинутый аудит очень важных котлет",
    funnyTitle: "Продвинутый аудит очень важных котлет",
    level: 4,
    price: 430,
    durationDays: 12,
    qualificationPoints: 78,
    unlockRequirements: { track: "pentester", minLevel: 3 },
  },
  {
    id: "pentest-digital-invasion",
    track: "pentester",
    title: "Великая книга цифрового вторжения без последствий",
    funnyTitle: "Великая книга цифрового вторжения без последствий",
    level: 5,
    price: 575,
    durationDays: 15,
    qualificationPoints: 106,
    unlockRequirements: { track: "pentester", minLevel: 4 },
  },
  {
    id: "pentest-vulnerabilities-devsecops",
    track: "pentester",
    title: "Повелитель уязвимостей и печального DevSecOps",
    funnyTitle: "Повелитель уязвимостей и печального DevSecOps",
    level: 5,
    price: 610,
    durationDays: 16,
    qualificationPoints: 112,
    unlockRequirements: { track: "pentester", minLevel: 4 },
  },
  {
    id: "analyst-fate-tables",
    track: "analyst",
    title: "Таблички судьбы и диаграммы рока",
    funnyTitle: "Таблички судьбы и диаграммы рока",
    level: 1,
    price: 85,
    durationDays: 3,
    qualificationPoints: 20,
  },
  {
    id: "analyst-uncomfortable-questions",
    track: "analyst",
    title: "Как задавать неудобные вопросы за деньги",
    funnyTitle: "Как задавать неудобные вопросы за деньги",
    level: 1,
    price: 95,
    durationDays: 4,
    qualificationPoints: 22,
  },
  {
    id: "analyst-metrics-nervous-client",
    track: "analyst",
    title: "Метрики, цифры и нервный заказчик",
    funnyTitle: "Метрики, цифры и нервный заказчик",
    level: 2,
    price: 150,
    durationDays: 5,
    qualificationPoints: 30,
  },
  {
    id: "analyst-sql-report-yesterday",
    track: "analyst",
    title: "SQL для людей, которым дали отчет вчера",
    funnyTitle: "SQL для людей, которым дали отчет вчера",
    level: 2,
    price: 165,
    durationDays: 6,
    qualificationPoints: 33,
  },
  {
    id: "analyst-data-meaninglessness",
    track: "analyst",
    title: "Смысл данных и бессмысленность презентаций",
    funnyTitle: "Смысл данных и бессмысленность презентаций",
    level: 3,
    price: 235,
    durationDays: 8,
    qualificationPoints: 45,
    unlockRequirements: { track: "analyst", minLevel: 2 },
  },
  {
    id: "analyst-dashboards-no-escape",
    track: "analyst",
    title: "Дашборды, от которых никто не уйдет",
    funnyTitle: "Дашборды, от которых никто не уйдет",
    level: 3,
    price: 255,
    durationDays: 8,
    qualificationPoints: 47,
    unlockRequirements: { track: "analyst", minLevel: 2 },
  },
  {
    id: "analyst-collective-panic",
    track: "analyst",
    title: "Аналитика в условиях коллективной паники",
    funnyTitle: "Аналитика в условиях коллективной паники",
    level: 4,
    price: 355,
    durationDays: 11,
    qualificationPoints: 68,
    unlockRequirements: { track: "analyst", minLevel: 3 },
  },
  {
    id: "analyst-deep-digging",
    track: "analyst",
    title: "Глубинное копание в цифрах и людях",
    funnyTitle: "Глубинное копание в цифрах и людях",
    level: 4,
    price: 385,
    durationDays: 11,
    qualificationPoints: 72,
    unlockRequirements: { track: "analyst", minLevel: 3 },
  },
  {
    id: "analyst-supreme-cause-effect",
    track: "analyst",
    title: "Верховная таблица причин и следствий",
    funnyTitle: "Верховная таблица причин и следствий",
    level: 5,
    price: 520,
    durationDays: 14,
    qualificationPoints: 100,
    unlockRequirements: { track: "analyst", minLevel: 4 },
  },
  {
    id: "analyst-gauss-household",
    track: "analyst",
    title: "Многополярная матрица Гаусса для бытовых нужд",
    funnyTitle: "Многополярная матрица Гаусса для бытовых нужд",
    level: 5,
    price: 560,
    durationDays: 15,
    qualificationPoints: 108,
    unlockRequirements: { track: "analyst", minLevel: 4 },
  },
  {
    id: "cto-people-and-systems",
    track: "cto",
    title: "Архитектура систем, людей и случайных решений",
    funnyTitle: "Архитектура систем, людей и случайных решений",
    level: 5,
    price: 650,
    durationDays: 16,
    qualificationPoints: 110,
    unlockRequirements: {
      anyOf: [
        { track: "backend", minLevel: 4 },
        { track: "frontend", minLevel: 4 },
        { track: "pm", minLevel: 4 },
      ],
    },
  },
  {
    id: "cto-manage-techies-not-eaten",
    track: "cto",
    title: "Как управлять технарями и не быть съеденным",
    funnyTitle: "Как управлять технарями и не быть съеденным",
    level: 5,
    price: 680,
    durationDays: 17,
    qualificationPoints: 112,
    unlockRequirements: {
      anyOf: [
        { track: "backend", minLevel: 5 },
        { track: "frontend", minLevel: 5 },
        { track: "pm", minLevel: 5 },
      ],
    },
  },
  {
    id: "cto-big-director-handbook",
    track: "cto",
    title: "Большой директорский справочник по срочному порядку",
    funnyTitle: "Большой директорский справочник по срочному порядку",
    level: 5,
    price: 730,
    durationDays: 18,
    qualificationPoints: 118,
    unlockRequirements: {
      allOf: [{ track: "pm", minLevel: 4 }],
      anyOf: [
        { track: "backend", minLevel: 5 },
        { track: "frontend", minLevel: 5 },
      ],
    },
  },
];

export const books: Book[] = baseBooks.map((book) => ({
  ...book,
  price: book.price * bookPriceMultiplier,
}));
