import type { OrderTemplate } from "../types";

export const orderTemplates: OrderTemplate[] = [
  {
    track: "qa",
    title: "Проверить калькулятор доставки картошки",
    funnyTitle: "Проверить калькулятор доставки картошки на 7 подозрительных нажатий",
    level: 1,
    durationDays: 2,
    rewardMoney: 35,
    rewardQualificationPoints: 6,
    isGolden: false,
    failureChancePct: 8,
    requirements: {
      minQualificationLevel: 1,
      minPcScore: 9,
      maxPcScore: 80,
      requiresWorkingPc: true,
    },
  },
  {
    track: "backend",
    title: "Написать API учета криков чаек",
    funnyTitle: "Написать API учета криков чаек",
    level: 2,
    durationDays: 5,
    rewardMoney: 120,
    rewardQualificationPoints: 12,
    isGolden: false,
    failureChancePct: 10,
    requirements: {
      minQualificationLevel: 2,
      minPcScore: 81,
      maxPcScore: 140,
      requiresWorkingPc: true,
    },
  },
  {
    track: "analyst",
    title: "Разобрать миграцию блох на коте",
    funnyTitle: "Разобрать миграцию блох на коте через спектральную статистику и табличную магию",
    level: 3,
    durationDays: 12,
    rewardMoney: 220,
    rewardQualificationPoints: 20,
    isGolden: false,
    failureChancePct: 12,
    requirements: {
      minQualificationLevel: 3,
      minPcScore: 141,
      maxPcScore: 200,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pm",
    title: "Подготовить проектный хаос-план",
    funnyTitle: "Подготовить проектный хаос-план для 12 отделов одновременно",
    level: 4,
    durationDays: 18,
    rewardMoney: 450,
    rewardQualificationPoints: 32,
    isGolden: false,
    failureChancePct: 14,
    requirements: {
      minQualificationLevel: 4,
      minPcScore: 201,
      maxPcScore: 260,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pentester",
    title: "Провести аудит межгалактического склада носков",
    funnyTitle: "Провести аудит безопасности межгалактического склада носков",
    level: 5,
    durationDays: 28,
    rewardMoney: 980,
    rewardQualificationPoints: 50,
    isGolden: false,
    failureChancePct: 16,
    requirements: {
      minQualificationLevel: 5,
      minPcScore: 261,
      maxPcScore: 360,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pm",
    title: "Золотой заказ: запуск завода баянов",
    funnyTitle: "Золотой заказ: координировать запуск завода умных баянов",
    level: 5,
    durationDays: 30,
    rewardMoney: 1180,
    rewardQualificationPoints: 50,
    isGolden: true,
    failureChancePct: 12,
    requirements: {
      minQualificationLevel: 5,
      minPcScore: 261,
      maxPcScore: 360,
      requiresWorkingPc: true,
    },
  },
];

