import type { OrderTemplate } from "../types";

export const orderTemplates: OrderTemplate[] = [
  {
    track: "qa",
    title: "Проверить калькулятор доставки картошки",
    funnyTitle: "Проверить калькулятор доставки картошки на 7 подозрительных нажатий",
    level: 1,
    durationDays: 2,
    rewardMoney: 350,
    rewardQualificationPoints: 6,
    isGolden: false,
    failureChancePct: 8,
    requirements: {
      minQualificationLevel: 1,
      minPcScore: 9,
      maxPcScore: 80,
      requiresWorkingPc: true,
    },
  },
  {
    track: "qa",
    title: "Разнести тестами портал аренды самокатов",
    funnyTitle: "Разнести тестами портал аренды самокатов и найти баг быстрее, чем он найдет прод",
    level: 2,
    durationDays: 5,
    rewardMoney: 1200,
    rewardQualificationPoints: 12,
    isGolden: false,
    failureChancePct: 9,
    requirements: {
      minQualificationLevel: 2,
      minPcScore: 81,
      maxPcScore: 140,
      requiresWorkingPc: true,
    },
  },
  {
    track: "qa",
    title: "Расследовать фантомные баги в банкомате",
    funnyTitle: "Расследовать фантомные баги в банкомате, который спорит с тест-кейсами как взрослый",
    level: 3,
    durationDays: 8,
    rewardMoney: 2100,
    rewardQualificationPoints: 20,
    isGolden: false,
    failureChancePct: 11,
    requirements: {
      minQualificationLevel: 3,
      minPcScore: 141,
      maxPcScore: 200,
      requiresWorkingPc: true,
    },
  },
  {
    track: "qa",
    title: "Возглавить тестовый шторм в банковском ядре",
    funnyTitle: "Возглавить тестовый шторм в банковском ядре и не дать релизу сбежать в пятницу вечером",
    level: 4,
    durationDays: 16,
    rewardMoney: 4300,
    rewardQualificationPoints: 30,
    isGolden: false,
    failureChancePct: 12,
    requirements: {
      minQualificationLevel: 4,
      minPcScore: 201,
      maxPcScore: 260,
      requiresWorkingPc: true,
    },
  },
  {
    track: "qa",
    title: "Золотой заказ: остановить апокалипсис регрессии",
    funnyTitle: "Золотой заказ: остановить апокалипсис регрессии и выжить после фразы 'да это маленькая правка'",
    level: 5,
    durationDays: 28,
    rewardMoney: 10200,
    rewardQualificationPoints: 52,
    isGolden: true,
    failureChancePct: 10,
    requirements: {
      minQualificationLevel: 5,
      minPcScore: 261,
      maxPcScore: 360,
      requiresWorkingPc: true,
    },
  },
  {
    track: "backend",
    title: "Подкрутить API учёта чаек",
    funnyTitle: "Подкрутить API учёта чаек так, чтобы чайки тоже не понимали, что там происходит",
    level: 1,
    durationDays: 3,
    rewardMoney: 450,
    rewardQualificationPoints: 7,
    isGolden: false,
    failureChancePct: 9,
    requirements: {
      minQualificationLevel: 1,
      minPcScore: 9,
      maxPcScore: 80,
      requiresWorkingPc: true,
    },
  },
  {
    track: "backend",
    title: "Написать API учета криков чаек",
    funnyTitle: "Написать API учета криков чаек",
    level: 2,
    durationDays: 5,
    rewardMoney: 1200,
    rewardQualificationPoints: 12,
    isGolden: false,
    failureChancePct: 10,
    requirements: {
      minQualificationLevel: 2,
      minPcScore: 81,
      maxPcScore: 140,
      requiresWorkingPc: true,
    },
  },
  {
    track: "backend",
    title: "Поднять сервис расписания котов-курьеров",
    funnyTitle: "Поднять сервис расписания котов-курьеров так, чтобы хвосты не ломали прод",
    level: 3,
    durationDays: 9,
    rewardMoney: 2150,
    rewardQualificationPoints: 20,
    isGolden: false,
    failureChancePct: 11,
    requirements: {
      minQualificationLevel: 3,
      minPcScore: 141,
      maxPcScore: 200,
      requiresWorkingPc: true,
    },
  },
  {
    track: "backend",
    title: "Пережить миграцию базы архива мемов",
    funnyTitle: "Пережить миграцию базы архива мемов и убедить всех, что rollback был частью плана",
    level: 4,
    durationDays: 17,
    rewardMoney: 4400,
    rewardQualificationPoints: 31,
    isGolden: false,
    failureChancePct: 13,
    requirements: {
      minQualificationLevel: 4,
      minPcScore: 201,
      maxPcScore: 260,
      requiresWorkingPc: true,
    },
  },
  {
    track: "backend",
    title: "Золотой заказ: укротить монолит госкофеварки",
    funnyTitle: "Золотой заказ: укротить монолит госкофеварки без жертв среди дежурной смены",
    level: 5,
    durationDays: 29,
    rewardMoney: 10400,
    rewardQualificationPoints: 52,
    isGolden: true,
    failureChancePct: 12,
    requirements: {
      minQualificationLevel: 5,
      minPcScore: 261,
      maxPcScore: 360,
      requiresWorkingPc: true,
    },
  },
  {
    track: "frontend",
    title: "Поправить лендинг клуба любителей табуреток",
    funnyTitle: "Поправить лендинг клуба любителей табуреток, чтобы кнопка не улетала в космос",
    level: 1,
    durationDays: 3,
    rewardMoney: 420,
    rewardQualificationPoints: 7,
    isGolden: false,
    failureChancePct: 8,
    requirements: {
      minQualificationLevel: 1,
      minPcScore: 9,
      maxPcScore: 80,
      requiresWorkingPc: true,
    },
  },
  {
    track: "frontend",
    title: "Починить адаптив кофейного стартапа",
    funnyTitle: "Починить адаптив кофейного стартапа, где меню на мобилке внезапно уезжает в Анапу",
    level: 2,
    durationDays: 5,
    rewardMoney: 1180,
    rewardQualificationPoints: 12,
    isGolden: false,
    failureChancePct: 9,
    requirements: {
      minQualificationLevel: 2,
      minPcScore: 81,
      maxPcScore: 140,
      requiresWorkingPc: true,
    },
  },
  {
    track: "frontend",
    title: "Собрать панель для нервного маркетинга",
    funnyTitle: "Собрать панель для нервного маркетинга, где каждый пиксель считает себя стратегическим",
    level: 3,
    durationDays: 8,
    rewardMoney: 2050,
    rewardQualificationPoints: 20,
    isGolden: false,
    failureChancePct: 11,
    requirements: {
      minQualificationLevel: 3,
      minPcScore: 141,
      maxPcScore: 200,
      requiresWorkingPc: true,
    },
  },
  {
    track: "frontend",
    title: "Пересобрать витрину цифрового банка",
    funnyTitle: "Пересобрать витрину цифрового банка так, чтобы анимации не съели весь процессор",
    level: 4,
    durationDays: 15,
    rewardMoney: 4250,
    rewardQualificationPoints: 30,
    isGolden: false,
    failureChancePct: 12,
    requirements: {
      minQualificationLevel: 4,
      minPcScore: 201,
      maxPcScore: 260,
      requiresWorkingPc: true,
    },
  },
  {
    track: "frontend",
    title: "Золотой заказ: приручить UI межзвёздного банка",
    funnyTitle: "Золотой заказ: приручить UI межзвёздного банка и не дать градиенту выиграть войну",
    level: 5,
    durationDays: 27,
    rewardMoney: 10100,
    rewardQualificationPoints: 51,
    isGolden: true,
    failureChancePct: 11,
    requirements: {
      minQualificationLevel: 5,
      minPcScore: 261,
      maxPcScore: 360,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pm",
    title: "Созвонить дедлайн по ремонту чайника",
    funnyTitle: "Созвонить дедлайн по ремонту чайника и сделать вид, что это roadmap",
    level: 1,
    durationDays: 3,
    rewardMoney: 400,
    rewardQualificationPoints: 6,
    isGolden: false,
    failureChancePct: 8,
    requirements: {
      minQualificationLevel: 1,
      minPcScore: 9,
      maxPcScore: 80,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pm",
    title: "Синхронизировать три команды и один холодильник",
    funnyTitle: "Синхронизировать три команды и один холодильник, который тоже хочет в приоритетный backlog",
    level: 2,
    durationDays: 6,
    rewardMoney: 1220,
    rewardQualificationPoints: 12,
    isGolden: false,
    failureChancePct: 10,
    requirements: {
      minQualificationLevel: 2,
      minPcScore: 81,
      maxPcScore: 140,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pm",
    title: "Разрулить релиз и истерику стейкхолдеров",
    funnyTitle: "Разрулить релиз и истерику стейкхолдеров так, чтобы все думали, что именно так и планировалось",
    level: 3,
    durationDays: 10,
    rewardMoney: 2250,
    rewardQualificationPoints: 21,
    isGolden: false,
    failureChancePct: 12,
    requirements: {
      minQualificationLevel: 3,
      minPcScore: 141,
      maxPcScore: 200,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pm",
    title: "Подготовить проектный хаос-план",
    funnyTitle: "Подготовить проектный хаос-план для 12 отделов одновременно",
    level: 4,
    durationDays: 18,
    rewardMoney: 4500,
    rewardQualificationPoints: 32,
    isGolden: false,
    failureChancePct: 14,
    requirements: {
      minQualificationLevel: 4,
      minPcScore: 201,
      maxPcScore: 260,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pm",
    title: "Золотой заказ: запуск завода баянов",
    funnyTitle: "Золотой заказ: координировать запуск завода умных баянов",
    level: 5,
    durationDays: 30,
    rewardMoney: 11800,
    rewardQualificationPoints: 50,
    isGolden: true,
    failureChancePct: 12,
    requirements: {
      minQualificationLevel: 5,
      minPcScore: 261,
      maxPcScore: 360,
      requiresWorkingPc: true,
    },
  },
  {
    track: "analyst",
    title: "Собрать отчёт по бегству кота от пылесоса",
    funnyTitle: "Собрать отчёт по бегству кота от пылесоса и не поссориться с реальностью",
    level: 1,
    durationDays: 4,
    rewardMoney: 440,
    rewardQualificationPoints: 7,
    isGolden: false,
    failureChancePct: 8,
    requirements: {
      minQualificationLevel: 1,
      minPcScore: 9,
      maxPcScore: 80,
      requiresWorkingPc: true,
    },
  },
  {
    track: "analyst",
    title: "Почистить дашборд тревожного маркетплейса",
    funnyTitle: "Почистить дашборд тревожного маркетплейса, где каждая метрика орёт в свой колокол",
    level: 2,
    durationDays: 6,
    rewardMoney: 1250,
    rewardQualificationPoints: 12,
    isGolden: false,
    failureChancePct: 9,
    requirements: {
      minQualificationLevel: 2,
      minPcScore: 81,
      maxPcScore: 140,
      requiresWorkingPc: true,
    },
  },
  {
    track: "analyst",
    title: "Разобрать миграцию блох на коте",
    funnyTitle: "Разобрать миграцию блох на коте через спектральную статистику и табличную магию",
    level: 3,
    durationDays: 12,
    rewardMoney: 2200,
    rewardQualificationPoints: 20,
    isGolden: false,
    failureChancePct: 12,
    requirements: {
      minQualificationLevel: 3,
      minPcScore: 141,
      maxPcScore: 200,
      requiresWorkingPc: true,
    },
  },
  {
    track: "analyst",
    title: "Предсказать отток пользователей пельменного SaaS",
    funnyTitle: "Предсказать отток пользователей пельменного SaaS и не превратить модель в мистический культ",
    level: 4,
    durationDays: 17,
    rewardMoney: 4380,
    rewardQualificationPoints: 31,
    isGolden: false,
    failureChancePct: 13,
    requirements: {
      minQualificationLevel: 4,
      minPcScore: 201,
      maxPcScore: 260,
      requiresWorkingPc: true,
    },
  },
  {
    track: "analyst",
    title: "Золотой заказ: посчитать экономику лунной доставки",
    funnyTitle: "Золотой заказ: посчитать экономику лунной доставки так, чтобы даже CFO перестал моргать",
    level: 5,
    durationDays: 28,
    rewardMoney: 10350,
    rewardQualificationPoints: 52,
    isGolden: true,
    failureChancePct: 11,
    requirements: {
      minQualificationLevel: 5,
      minPcScore: 261,
      maxPcScore: 360,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pentester",
    title: "Проверить пароль от подъездного домофона",
    funnyTitle: "Проверить пароль от домофона, который почему-то совпадает с '1234 и надежда'",
    level: 1,
    durationDays: 2,
    rewardMoney: 460,
    rewardQualificationPoints: 7,
    isGolden: false,
    failureChancePct: 10,
    requirements: {
      minQualificationLevel: 1,
      minPcScore: 9,
      maxPcScore: 80,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pentester",
    title: "Поймать дыру в CRM шиномонтажа",
    funnyTitle: "Поймать дыру в CRM шиномонтажа до того, как её найдет соседский школьник",
    level: 2,
    durationDays: 5,
    rewardMoney: 1240,
    rewardQualificationPoints: 12,
    isGolden: false,
    failureChancePct: 10,
    requirements: {
      minQualificationLevel: 2,
      minPcScore: 81,
      maxPcScore: 140,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pentester",
    title: "Разобрать утечку в чате коллекционеров роутеров",
    funnyTitle: "Разобрать утечку в чате коллекционеров роутеров и остаться формально в белой зоне",
    level: 3,
    durationDays: 9,
    rewardMoney: 2180,
    rewardQualificationPoints: 20,
    isGolden: false,
    failureChancePct: 12,
    requirements: {
      minQualificationLevel: 3,
      minPcScore: 141,
      maxPcScore: 200,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pentester",
    title: "Устроить аудит безопасности банка тостеров",
    funnyTitle: "Устроить аудит безопасности банка тостеров и доказать, что тосты не должны иметь root",
    level: 4,
    durationDays: 16,
    rewardMoney: 4450,
    rewardQualificationPoints: 31,
    isGolden: false,
    failureChancePct: 14,
    requirements: {
      minQualificationLevel: 4,
      minPcScore: 201,
      maxPcScore: 260,
      requiresWorkingPc: true,
    },
  },
  {
    track: "pentester",
    title: "Провести аудит межгалактического склада носков",
    funnyTitle: "Провести аудит безопасности межгалактического склада носков",
    level: 5,
    durationDays: 28,
    rewardMoney: 9800,
    rewardQualificationPoints: 50,
    isGolden: true,
    failureChancePct: 16,
    requirements: {
      minQualificationLevel: 5,
      minPcScore: 261,
      maxPcScore: 360,
      requiresWorkingPc: true,
    },
  },
];
