import type { VacancyTemplate } from "../types";

export const vacancyTemplates: VacancyTemplate[] = [
  {
    track: "qa",
    formalTitle: "Junior QA",
    funnyTitle: "Младший искатель багов у лысых рыб",
    careerLevel: 1,
    baseSalary: 1400,
    companyModifierPct: 0,
    isGolden: false,
    requirements: { requiredTrack: "qa", requiredQualificationLevel: 1 },
  },
  {
    track: "qa",
    formalTitle: "Middle QA",
    funnyTitle: "Проверяющий релизы до того, как они проверят нервы команды",
    careerLevel: 3,
    baseSalary: 2400,
    companyModifierPct: 0,
    isGolden: false,
    requirements: { requiredTrack: "qa", requiredQualificationLevel: 2, requiredQualificationPoints: 90 },
  },
  {
    track: "qa",
    formalTitle: "Senior QA",
    funnyTitle: "Старший повелитель тест-кейсов",
    careerLevel: 5,
    baseSalary: 3700,
    companyModifierPct: 0,
    isGolden: false,
    requirements: { requiredTrack: "qa", requiredQualificationLevel: 3, requiredQualificationPoints: 220 },
  },
  {
    track: "backend",
    formalTitle: "Junior Backend Engineer",
    funnyTitle: "Ковырятель серверов коровника",
    careerLevel: 1,
    baseSalary: 1900,
    companyModifierPct: 0,
    isGolden: false,
    requirements: { requiredTrack: "backend", requiredQualificationLevel: 1 },
  },
  {
    track: "backend",
    formalTitle: "Middle Backend Engineer",
    funnyTitle: "Укротитель очередей, кэшей и упрямых API",
    careerLevel: 3,
    baseSalary: 3200,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "backend",
      requiredQualificationLevel: 2,
      requiredQualificationPoints: 130,
    },
  },
  {
    track: "backend",
    formalTitle: "Senior Backend Engineer",
    funnyTitle: "Главный переговорщик с высокими нагрузками",
    careerLevel: 5,
    baseSalary: 4700,
    companyModifierPct: 0,
    isGolden: true,
    requirements: {
      requiredTrack: "backend",
      requiredQualificationLevel: 4,
      requiredQualificationPoints: 320,
    },
  },
  {
    track: "frontend",
    formalTitle: "Junior Frontend Engineer",
    funnyTitle: "Выравниватель кнопок в браузере бабушки",
    careerLevel: 1,
    baseSalary: 1800,
    companyModifierPct: 0,
    isGolden: false,
    requirements: { requiredTrack: "frontend", requiredQualificationLevel: 1 },
  },
  {
    track: "frontend",
    formalTitle: "Middle Frontend Engineer",
    funnyTitle: "Собирает интерфейсы без истерики и с сеткой",
    careerLevel: 3,
    baseSalary: 3000,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "frontend",
      requiredQualificationLevel: 2,
      requiredQualificationPoints: 120,
    },
  },
  {
    track: "frontend",
    formalTitle: "Senior Frontend Engineer",
    funnyTitle: "Главный по интерфейсам, анимациям и болям продакшена",
    careerLevel: 5,
    baseSalary: 4500,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "frontend",
      requiredQualificationLevel: 4,
      requiredQualificationPoints: 300,
    },
  },
  {
    track: "analyst",
    formalTitle: "Junior Analyst",
    funnyTitle: "Толкователь таблиц и повелитель внезапных инсайтов",
    careerLevel: 1,
    baseSalary: 1700,
    companyModifierPct: 0,
    isGolden: false,
    requirements: { requiredTrack: "analyst", requiredQualificationLevel: 1 },
  },
  {
    track: "analyst",
    formalTitle: "Middle Analyst",
    funnyTitle: "Разбирает хаос в цифрах и выживает после созвонов",
    careerLevel: 3,
    baseSalary: 2950,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "analyst",
      requiredQualificationLevel: 2,
      requiredQualificationPoints: 110,
    },
  },
  {
    track: "analyst",
    formalTitle: "Senior Analyst",
    funnyTitle: "Старший архитектор дашбордов, гипотез и неприятной правды",
    careerLevel: 5,
    baseSalary: 4300,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "analyst",
      requiredQualificationLevel: 4,
      requiredQualificationPoints: 280,
    },
  },
  {
    track: "pm",
    formalTitle: "Junior PM",
    funnyTitle: "Координатор дедлайнов, которых никто не видел",
    careerLevel: 1,
    baseSalary: 2000,
    companyModifierPct: 0,
    isGolden: false,
    requirements: { requiredTrack: "pm", requiredQualificationLevel: 1 },
  },
  {
    track: "pm",
    formalTitle: "Middle PM",
    funnyTitle: "Управляет хаосом так, будто он хотя бы наполовину согласован",
    careerLevel: 3,
    baseSalary: 3400,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "pm",
      requiredQualificationLevel: 2,
      requiredQualificationPoints: 100,
    },
  },
  {
    track: "pm",
    formalTitle: "Senior PM",
    funnyTitle: "Разруливает релизы, бюджеты и коллективный нервный тик",
    careerLevel: 5,
    baseSalary: 4900,
    companyModifierPct: 0,
    isGolden: true,
    requirements: {
      requiredTrack: "pm",
      requiredQualificationLevel: 4,
      requiredQualificationPoints: 260,
    },
  },
  {
    track: "pentester",
    formalTitle: "Junior Pentester",
    funnyTitle: "Младший искатель дыр в заборах и системах",
    careerLevel: 1,
    baseSalary: 2100,
    companyModifierPct: 0,
    isGolden: false,
    requirements: { requiredTrack: "pentester", requiredQualificationLevel: 1 },
  },
  {
    track: "pentester",
    formalTitle: "Middle Pentester",
    funnyTitle: "Ломает аккуратно, документирует беспощадно",
    careerLevel: 3,
    baseSalary: 3600,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "pentester",
      requiredQualificationLevel: 3,
      requiredQualificationPoints: 180,
    },
  },
  {
    track: "pentester",
    formalTitle: "Senior Pentester",
    funnyTitle: "Старший аудит безопасности и ночных кошмаров инфраструктуры",
    careerLevel: 5,
    baseSalary: 5200,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "pentester",
      requiredQualificationLevel: 4,
      requiredQualificationPoints: 320,
    },
  },
];
