import type { VacancyTemplate } from "../types";

export const vacancyTemplates: VacancyTemplate[] = [
  {
    track: "qa",
    formalTitle: "Junior QA",
    funnyTitle: "Младший искатель багов у лысых рыб",
    careerLevel: 1,
    baseSalary: 1400,
    companyModifierPct: 0,
    isGolden: false,
    requirements: { requiredTrack: "qa", requiredQualificationLevel: 1 },
  },
  {
    track: "qa",
    formalTitle: "Senior QA",
    funnyTitle: "Старший повелитель тест-кейсов",
    careerLevel: 5,
    baseSalary: 3700,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "qa",
      requiredQualificationLevel: 3,
      requiredQualificationPoints: 220,
    },
  },
  {
    track: "backend",
    formalTitle: "Junior Backend Engineer",
    funnyTitle: "Ковырятель серверов коровника",
    careerLevel: 1,
    baseSalary: 1900,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "backend",
      requiredQualificationLevel: 1,
      requiredPreviousTrack: ["qa"],
      requiredPreviousTitle: ["Senior QA"],
    },
  },
  {
    track: "frontend",
    formalTitle: "Junior Frontend Engineer",
    funnyTitle: "Выравниватель кнопок в браузере бабушки",
    careerLevel: 1,
    baseSalary: 1800,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "frontend",
      requiredQualificationLevel: 1,
      requiredPreviousTrack: ["qa"],
      requiredPreviousTitle: ["Senior QA"],
    },
  },
  {
    track: "pm",
    formalTitle: "Junior PM",
    funnyTitle: "Координатор дедлайнов, которых никто не видел",
    careerLevel: 1,
    baseSalary: 2000,
    companyModifierPct: 0,
    isGolden: false,
    requirements: {
      requiredTrack: "pm",
      requiredQualificationLevel: 1,
      requiredPreviousTrack: ["qa", "backend", "frontend"],
      requiredPreviousTitle: ["Senior QA", "Senior Backend Engineer", "Senior Frontend Engineer"],
    },
  },
  {
    track: "backend",
    formalTitle: "Junior Backend Engineer",
    funnyTitle: "Золотая вакансия: Ковырятель серверов коровника высшей категории",
    careerLevel: 1,
    baseSalary: 1900,
    companyModifierPct: 20,
    isGolden: true,
    requirements: {
      requiredTrack: "backend",
      requiredQualificationLevel: 1,
      requiredPreviousTrack: ["qa"],
      requiredPreviousTitle: ["Senior QA"],
    },
  },
];

